name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_native:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check native build
      run: |
        git submodule update --init
        cd C_Controller
        target=native
        mkdir -p _build_${target}
        cd _build_${target}
        cmake .. -DCMAKE_BUILD_TYPE=Release -DTARGET=${target}
        make -j$(nproc)

  build_stm32f303:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.

    - name: Check stm32 build
      run: |
        git submodule update --init
        cd C_Controller
        target=stm32f303
        mkdir -p _build_${target}
        cd _build_${target}
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DTARGET=${target}
        make -j$(nproc)
